### ISSUE TITLE
Slicing a DataFrame

### ISSUE THREAD

**Issue by Rotaerk** [achirkin/fasttensor#14]
Is there some way to take, say, a `Vector _ 10` and drop the last 5 elements to get a `Vector _ 5`?  In Vulkan, there are cases where the size of the array that Vulkan returned is much larger than the number of actual valid elements.

For example, within `VkPhysicalDeviceMemoryProperties`, the `memoryHeaps` field is an array that always has length `VK_MAX_MEMORY_HEAPS`, but only the first `memoryHeapCount` elements are actually valid.

I would like to be able to, say, fold over these elements.  As it stands, the only way I can see to do it is to first convert it to a list, and then use the standard list functions for that.

**Comment by achirkin** [comment]
Hm, probably, there is no such function in `Numeric.DataFrame.SubSpace` right now. I definitely need to implement it.

On the good side, you still can do it via `unsafeThawDataFrame` + [`copyMutableDataFrame`](https://github.com/achirkin/easytensor/blob/75dc180c08ceb2321a6eca526a45739da34f646c/easytensor/src/Numeric/DataFrame/ST.hs#L94-L101) + `unsafeFreezeDataFrame`. It is ok to use unsafe thaw/freeze as long as you don't really modify them.

Implementing such a function is a little tricky, because sometimes it requires copying data, sometimes doesn't.

Another thing is that since you use the vectors in Vulkan, you always have to check if the underlying arrays are pinned. Normally, `easytensor-vulkan` helpers do that for you.

If you want to fold over the part of the vector, you can use indexed folds, such as `iwfoldl` or `iwfoldMap` and discard elements based on their indices. Not super efficient, but you don't need to copy elements at least.

**Comment by achirkin** [comment]
This function is implemented now, available in [Numeric.DataFrame.SubSpace.slice](https://github.com/achirkin/easytensor/blob/f9b7415d1646b3c58084d58ff4b68486b5fedcb7/easytensor/src/Numeric/DataFrame/SubSpace.hs#L106-L108).

I am closing the issue, but feel free to reopen it if there are any problems.
