### ISSUE TITLE
Why is Idx bounded to 0 < i =< Dim d?

### ISSUE THREAD

**Issue by stites** [achirkin/fasttensor#5]
Wouldn't `0 =< i < Dim d` be more programmer-friendly? I realize there is an escape hatch with `fromEnum`, but I'm wondering if there is a specific reason behind this interface.

**Comment by achirkin** [comment]
I guess, there is a typo somewhere in your question. Do you mean, why do I use range `[1..Dim d]` instead of `[0..Dim d - 1]`? Honestly, this was a really hard question for me. In the end, I wanted to use Matlab- and R-like indexing, both of which start with 1 instead of 0. Even though this brings all sorts of problems with `Enum` instances and necessity to differentiate offsets and 1D indexes.
But let's keep this issue here for a discussion if changing 1-based to 0-based indexing worth something and if it is feasible to migrate in the current state of the libraries.

**Comment by stites** [comment]
Yes -- fixed the typo!

I think the tradeoffs here are wind up being about beginner-friendliness for programmers vs non-programmers. I will point out that it does break the cognitive mold of what a Haskell programmer might expect and it's a little funky since Dim is 0-indexed.

In an ideal world where pytorch users start migrating to haskell + hasktorch, I'm a little nervous that they will also be confused because of python's 0-indexed API.

**Comment by achirkin** [comment]
A little note here, it is not fully correct to say that Dim is 0-indexed :) If you have an object with zero dimension along one of its axes, it contains nothing, which is very clear from conditions `1 <= Idx 0 <= 0` (also note, this is different from empty `Dims []`, which is totally valid scalar indexed by a unit `Idxs []`).
Another small thing in favor of 1-indexing is that GHC.TypeLits provides `(<=)` operator for type-level nats, but does not provide `(<)` operator (even though, it can be easily implemented via `CmpNat`).

**Comment by achirkin** [comment]
After a long rethinking of this long standing issue, I decided to move `dimensions` and `easytensor` to 0-based indexing.
So, this is "fixed" since version 2 of easytensor :)
