### ISSUE TITLE
HomTransform4 not implemented

### ISSUE THREAD

**Issue by Rotaerk** [achirkin/fasttensor#8]
I'm at the point in the vulkan tutorials where I have need of these transforms.  I'd like to make an attempt at implementing them, but I'm unclear on the intent behind and plan for the existing `HomTransform4` class.  Basically, why is it a class at all, rather than just having free functions that are constrained to `Floating t =>` or something?  What other instances would there be besides Float and Double?

**Comment by achirkin** [comment]
Hmm, I have implemented it in older versions of easytensor or fastvec. And I have not touched the interface yet - maybe it is worth rethinking.

The idea behind this to be a class was a specialization, because it is supposed to be performance-critical code. It is the same as in `Numeric/Quaternion/Class.hs` + `Numeric/Quaternion/QFloat.hs` + `Numeric/Quaternion/QDouble.hs`:

  * To have only two instances: for `Float` and `Double`
  * To know constructors of all `DataFrame` types involved inside the implementations
  * ... and thus avoid using any other classes/instances inside the implementations.


....

Looked up: in `easytensor`, I had `HomTransform4` implemented only in GHCJS version [https://github.com/achirkin/easytensor/tree/8925038bc9f2347a64c34035ca3657b0bdcb482c/easytensor/src-ghcjs/Numeric/Matrix](https://github.com/achirkin/easytensor/tree/8925038bc9f2347a64c34035ca3657b0bdcb482c/easytensor/src-ghcjs/Numeric/Matrix).
Note for the implementation, **the matrices in `easytensor` are column-first**.

**Comment by Rotaerk** [comment]
I need a function to test if two vectors or two matrices are approximately equivalent.  I think I need to use `ewzip` and `ewfoldl`to implement such a thing, but I'm not sure how to use these functions.  Could you provide examples?

**Comment by achirkin** [comment]
Something like this should work:
```Haskell
almostEq a b = (eps >=) . ewfoldl @_ @[] max 0 . abs $ a - b
```
The second type argument here makes sure the elements of the fold are scalars (overwise it is likely to complain about ambiguous types).

**Comment by achirkin** [comment]
Implemented via https://github.com/achirkin/easytensor/pull/10 and https://github.com/achirkin/easytensor/pull/12 .
